name: Deploy MkDocs

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências MkDocs
      run: |
        pip install mkdocs mkdocs-material

    - name: Gerar e publicar site
      run: mkdocs gh-deploy --force
